from core.src import db 
import pandas as pd
class Trackers(db.Document):
    tracker_id = db.StringField(required=True, unique=True)
    creation_date = db.DateTimeField(default=pd.Timestamp.utcnow)
    name = db.StringField(required=True)
    asset_class = db.StringField()
    theme = db.StringField()
    direction = db.StringField(required=True)
    portal_name = db.StringField()
    tickers = db.ListField(db.StringField(required=True))
    weights = db.DictField(required=True)
    lbound_weights = db.DictField(required=True)
    ubound_weights = db.DictField(required=True)
    volatility_target = db.FloatField(required=True, min_value=0)
    volatility_max = db.FloatField(required=True, min_value=0)
    volatility_tolerance = db.FloatField(required = True, min_value=0)
    volatility_duration = db.IntField(required=True,  min_value=0)
    notional = db.FloatField(required=True, min_value=0)
    calibration_volume_threshold = db.FloatField(required=True, min_value=0)
    leverage = db.FloatField(required=True)
    min_risky = db.FloatField(required=True)
    gonogo_return = db.FloatField(required=True)
    gonogo_weight = db.FloatField(required=True)
    max_uncalibrate = db.IntField(required=True)
    factsheet_link = db.StringField()
    performances = db.DictField()
    benchmark = db.StringField()
    retails_units = db.DictField()